# Copyright IBM Corp. 2016  All Rights Reserved.

title: IBM Verse Developer Extension for Google Chrome

description: >
  "This site contains a tutorial and reference documentation for IBM Verse Developer Extension for Google Chrome."
baseurl: "https://ibmcnxdev.github.io/verse-developer-chrome-ext" # the url for this documentation site
url: "https://github.com" # the base hostname & protocol for your site
verse-developer-chrome-ext: "https://github.com/ibmcnxdev/verse-developer-chrome-ext"

name: Tutorials for Verse Extension
markdown: kramdown

collections:
  tutorials:
    output: true
  reference:
    output: true
